'use client';
import {useState} from 'react';
import {ArrowUpRight,Check} from 'lucide-react';
import {Checkbox} from '@/components/ui/checkbox';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
const categories=['建築・リフォームの相談','プロジェクト全体の相談','IT・業務改善の相談','その他・まだ決まっていない'];
export default function Contact(){const [category,setCategory]=useState(categories[0]);const [consent,setConsent]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [receipt,setReceipt]=useState('');const [notificationAccepted,setNotificationAccepted]=useState(false);
async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!consent){setError('個人情報の取り扱いへの同意をお願いします。');return;}const data=new FormData(e.currentTarget);setBusy(true);setError('');try{const r=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...Object.fromEntries(data),category,consent})});const result=await r.json();if(!r.ok)throw new Error(result.error||'送信できませんでした。');setNotificationAccepted(result.notificationAccepted===true);setReceipt(result.receipt);}catch(err){setError(err instanceof Error?err.message:'通信に失敗しました。入力内容は残っています。再度お試しください。');}finally{setBusy(false);}}
return <div>{receipt ? <div className="form-success" role="status"><Check size={30}/><h3>ご相談を受け付けました。</h3><p>お問い合わせありがとうございます。<br/>内容を確認のうえ、ご記入の連絡先へご連絡します。</p>{!notificationAccepted&&<p className="form-error">内容は保存されましたが、担当者へのメール通知を確認できませんでした。お急ぎの場合は、受付番号を添えて <a href="mailto:info@greenhomecons.net">info@greenhomecons.net</a> へご連絡ください。</p>}<p className="micro">受付番号：{receipt}</p><p className="micro">自動返信メールは送信されません。この画面を控えとして保存してください。</p><button className="button" onClick={()=>{setReceipt('');setConsent(false)}} style={{marginTop:20}}>別の相談を送る</button></div>:<form onSubmit={submit}><div className="field"><label htmlFor="category">ご相談の分野<b>必須</b></label><Select value={category} onValueChange={setCategory}><SelectTrigger id="category"><SelectValue/></SelectTrigger><SelectContent>{categories.map(x=><SelectItem value={x} key={x}>{x}</SelectItem>)}</SelectContent></Select></div><div className="form-grid"><label className="field">お名前 <b>必須</b><input name="name" required maxLength={100} autoComplete="name" placeholder="山田 太郎"/></label><label className="field">会社名 <b>任意</b><input name="company" maxLength={150} autoComplete="organization" placeholder="法人のお客様はこちら"/></label></div><label className="field">メールアドレス <b>必須</b><input name="email" type="email" required maxLength={254} autoComplete="email" placeholder="example@email.com"/></label><label className="field">電話番号 <b>任意</b><input name="phone" type="tel" maxLength={40} autoComplete="tel" placeholder="電話での連絡をご希望の場合"/></label><label className="field">ご相談内容 <b>必須</b><textarea name="message" required minLength={10} maxLength={5000} rows={5} placeholder="お困りごとや、ご検討中の内容をお聞かせください。（10文字以上）"/></label><label className="hp" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off"/></label><div className="consent"><Checkbox id="consent" checked={consent} onCheckedChange={v=>setConsent(v===true)}/><label htmlFor="consent">下記の個人情報の取り扱いに同意する</label></div>{error&&<p className="form-error" role="alert">{error}</p>}<button className="button" type="submit" disabled={busy}>{busy?'送信しています…':'この内容で相談を送る'}<ArrowUpRight size={20}/></button></form>}<details className="privacy" id="privacy"><summary>個人情報の取り扱い</summary><p>合同会社グリーンホームコンサルは、お名前・連絡先・ご相談内容を、お問い合わせへの回答およびご依頼に関する連絡のために利用します。入力内容は安全管理に配慮したクラウド環境に保存し、法令に基づく場合を除き、ご本人の同意なく第三者へ提供しません。業務委託先については適切な管理を行います。</p><p>不要になった情報は適切に削除します。開示・訂正・削除のご希望も本フォームからお知らせください。本人確認のうえ対応します。機微な個人情報やパスワードは記入しないでください。</p></details></div>}
