import {ArrowUpRight, Handshake, Layers3, Cpu, MoveRight} from 'lucide-react';
import Contact from './contact';
import {projects} from './projects';
const services=[{n:'01',en:'CONSULTING',icon:Handshake,title:<>施主の味方になる<br/>建築コンサルティング</>,text:'見積もりや提案に迷ったときのセカンドオピニオン。複数の業者との調整や現場の確認を通じて、安心して任せられる進め方を一緒に考えます。',items:['見積もり・工事内容の比較検討','施工業者・専門家の選定と調整','水回り、一部屋など部分改装の相談','現場の進行・品質に関するサポート']},{n:'02',en:'PROJECT SUPPORT',icon:Layers3,title:<>点ではなく、全体で。<br/>プロジェクトを支える</>,text:'一級・二級建築士、建築施工管理技士、宅地建物取引士の知見をつなぎ、仕入れから企画・設計・現場統括・販売まで、全体を見通した窓口となります。',items:['土地・建物の検討、事業計画の相談','住宅・店舗の企画と設計支援','施工体制の構築と現場統括','販売・活用を見据えた計画づくり']},{n:'03',en:'IT & BUSINESS',icon:Cpu,title:<>ITで、日々の仕事を<br/>もっと使いやすく</>,text:'システム開発の長年の経験をもとに、業務の整理からソフトウェア・AIの活用まで支援。建築に関わる業務はもちろん、異なる業種のご相談もお受けします。',items:['業務改善・システム導入の相談','ウェブサービス・ソフトウェア開発','AIを活用した業務効率化','導入後の運用・改善サポート']}];
const companyDetails=[['会社名','合同会社グリーンホームコンサル'],['所在地','東京都青梅市根ヶ布２−１３６８−５８'],['代表社員','横林絹代'],['設立年月日','２０２６年９月４日'],['資本金','5,000,000円（建設業許可 準備中）']];
const businessDomains=['建築物の企画、設計に関するコンサルティング','住宅、店舗などの新築、増築、改築、修繕、内装及びリフォームのご相談','飲食店、喫茶店の企画及び経営コンサル','AIなどを利用した建築工事システムの企画、設計、開発'];
export default function Home(){return <>
<a className="skip" href="#main">本文へ移動</a>
<header className="header"><a className="brand" href="#" aria-label="グリーンホームコンサル トップへ"><img src="/greenhome-consult-logo.png" alt="GREEN HOME CONSULT グリーンホームコンサル"/></a><nav aria-label="メインナビゲーション"><a href="#company">会社概要</a><a href="#approach">私たちについて</a><a href="#services">できること</a><a href="#works">事例</a><a className="nav-contact" href="#contact">ご相談はこちら <ArrowUpRight size={17}/></a></nav></header>
<main id="main"><section className="hero"><div className="hero-copy"><p className="eyebrow">ARCHITECTURE × CONSULTING × IT</p><h1>建物のこと。<br/>その先のこと。<br/><em>頼れる相談相手に。</em></h1><p className="hero-lead">小さなリフォームから、事業の未来まで。<br/>建築とITの経験で、あなたの「どうしよう」を<br className="desktop"/>一緒に、納得できる答えへ。</p><a className="button" href="#contact">まずは相談してみる <ArrowUpRight size={20}/></a><p className="micro">計画が固まっていなくても、ご相談ください。</p></div><figure className="hero-image"><img src="/house-hero.jpg" alt="木の素材と自然光を生かした住空間のイメージ"/><figcaption>暮らしと、事業の可能性を。<small>SPACE & POSSIBILITY</small></figcaption><span className="image-label">イメージ写真／当社施工事例ではありません</span></figure><div className="hero-bottom"><span>施主の視点から、全体を見渡す。</span><a href="#approach">私たちの考え方 <MoveRight size={19}/></a></div></section>
<section id="approach" className="section approach"><div><p className="eyebrow">OUR APPROACH</p><h2>つくる前から。<br/>使い続ける、その先まで。</h2></div><div className="approach-body"><p className="intro">「誰に相談すればいいのか」<br/>そんなとき、最初に思い出していただける存在へ。</p><p>私たちは、建築・リフォームとITの知見を持つ、家族を中心とした小さなチームです。長年現場に向き合ってきた経験を生かし、お客様の立場から計画を整理します。</p><p>一つの会社の提案だけで決めるのではなく、複数の選択肢を比較し、必要な専門家や施工業者をつなぐ。規模の大小にかかわらず、顔の見える関係で、一つひとつ丁寧に伴走します。</p><div className="experience"><div><strong>30<span>年以上</span></strong><p>建築・リフォームに携わる経験</p></div><div><strong>20<span>年以上</span></strong><p>大手システム開発会社での経験</p></div></div><p className="micro">所属メンバーの経歴です。法人としての創業年数ではありません。</p></div></section>
<section id="services" className="services section"><div className="section-top"><div><p className="eyebrow">THREE PILLARS</p><h2>ハードからソフトまで。<br/>3つの力で支えます。</h2></div><p>建物だけでなく、その中で営まれる<br/>暮らしとビジネスまで考える。</p></div><div className="service-grid">{services.map(s=><article key={s.n}><div className="service-number">{s.n}<s.icon size={29} strokeWidth={1.2}/></div><p className="small-en">{s.en}</p><h3>{s.title}</h3><p>{s.text}</p><ul>{s.items.map(x=><li key={x}>{x}</li>)}</ul><a href="#contact">この分野について相談する <ArrowUpRight size={18}/></a></article>)}</div><p className="service-note">資格の保有と法人としての許認可は異なります。設計・工事監理、工事請負、不動産取引等は、必要な登録・許可および業務範囲を確認し、対応可能な体制をご案内します。</p></section>
<section className="process section"><p className="eyebrow">ONE POINT OF CONTACT</p><h2>ひとつの窓口で、プロジェクトをつなぐ。</h2><div className="phases">{['仕入れ','企画','設計','現場統括','販売・活用'].map((x,i)=><div key={x}><span>0{i+1}</span><h3>{x}</h3></div>)}</div><p>すべての工程でも、必要な工程だけでも。建築とITの両面から、無理のない進め方をご提案します。</p></section>
<section id="works" className="works section"><div className="section-top"><div><p className="eyebrow">PROJECT STORIES</p><h2>一つひとつの、取り組み。</h2></div><span className="outline-tag">事例は順次公開予定</span></div>{projects.length ? <div className="project-list">{projects.map(p=><article key={p.title}><p>{p.category}</p><h3>{p.title}</h3><p>{p.description}</p></article>)}</div>:<div className="works-empty"><span className="big-index">WORKS</span><div><h3>これまでの経験を、<br/>これからの事例へ。</h3><p>掲載許可をいただいた取り組みから、相談の背景や解決までのプロセスをご紹介していきます。<br/>ご相談に近い経験については、お問い合わせ時にお尋ねください。</p></div></div>}</section>
<section id="company" className="section company"><div className="company-intro"><p className="eyebrow">COMPANY PROFILE</p><h2>会社概要</h2><p>建築・店舗づくりから、飲食・ITまで。<br/>それぞれの経験を生かし、事業の課題に伴走します。</p></div><div className="company-details"><dl>{companyDetails.map(([a,b])=><div key={a}><dt>{a}</dt><dd>{b}</dd></div>)}</dl><div className="company-business"><p className="company-label">事業領域</p><ul>{businessDomains.map(business=><li key={business}>{business}</li>)}</ul></div><dl className="company-qualifications"><div><dt>所属資格者</dt><dd>一級建築士・二級建築士・建築施工管理技士・宅地建物取引士</dd></div></dl></div></section>
<section id="contact" className="section contact"><div className="contact-heading"><p className="eyebrow">LET’S TALK</p><h2>小さな「困った」から、<br/>お聞かせください。</h2><p>「この見積もり、どうだろう」<br/>「一部だけ直したい」<br/>「業務をもっと楽にしたい」</p><p>まだ具体的な計画がなくても大丈夫です。<br/>ご相談の内容を確認し、ご連絡します。</p></div><Contact/></section></main>
<footer><a className="footer-brand" href="#" aria-label="グリーンホームコンサル トップへ"><img src="/greenhome-consult-logo.png" alt="GREEN HOME CONSULT グリーンホームコンサル"/></a><p>建築とITで、暮らしと事業に寄り添う。</p><div><span>© Green Home Consult</span><a href="#privacy">個人情報の取り扱い</a></div><p className="photo-credit">Photo: <a href="https://unsplash.com/photos/brown-wooden-bench-near-window-SoNaNOFT974" target="_blank" rel="noreferrer">Daniel Chen / Unsplash</a></p></footer></>}
